# Generated by Django 4.2.7 on 2023-11-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_maqola_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maqola',
        ),
    ]
