# Generated by Django 4.2.7 on 2023-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
